name: patch
on:
 pull_request:
   branches:
     - release/**
   types:
     - closed
jobs:
 main:
   runs-on: ubuntu-latest
   if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'patch/')
   steps:
     - uses: EndBug/add-and-commit@v9
       with:
           author_name: Alex Kaszynski
           author_email: akascap@gmail.com
           tag: '`python -c "import pyvista as pv; print(pv.__version__)"`'

